import type {
  Employer,
  FarmOpportunity,
  ImpactMetric,
  Job,
  ServiceRequest,
  Worker,
} from './types'

export const workers: Worker[] = [
  {
    id: 'meena',
    name: 'Meena Devi',
    hindiName: 'मीना देवी',
    segment: 'women-returning',
    role: 'Tailoring worker returning to paid work',
    location: 'Jaipur, Rajasthan',
    distancePreferenceKm: 5,
    languages: ['Hindi', 'Marwari'],
    skills: ['Tailoring', 'Alterations', 'Quality check', 'Customer handling'],
    verifiedSkills: ['Tailoring', 'Alterations'],
    weeklyIncomeTarget: 4200,
    earnedThisWeek: 2150,
    pendingPayments: 700,
    completedShifts: 4,
    availability: ['Morning', 'Afternoon'],
    experience: '3 years home-based tailoring',
    workPreference: 'Nearby day shifts with clear payment',
    documents: ['Aadhaar', 'Bank account', 'Self-help group reference'],
    womenWorkMode: {
      enabled: true,
      preferredHours: '9 AM - 3 PM',
      nearbyOnly: true,
      childcareNote: 'Needs school pickup buffer after 3 PM',
    },
    enterpriseProfile: {
      serviceName: 'Blouse stitching and school uniform repairs',
      priceRange: 'Rs 80 - Rs 350 per order',
      repeatCustomers: 18,
      monthlyGoal: 16000,
    },
  },
  {
    id: 'rahul',
    name: 'Rahul Kumar',
    hindiName: 'राहुल कुमार',
    segment: 'first-time',
    role: 'First-time warehouse and delivery worker',
    location: 'Patna, Bihar',
    distancePreferenceKm: 8,
    languages: ['Hindi', 'Bhojpuri'],
    skills: ['Packing', 'Inventory sorting', 'Smartphone use', 'Basic English'],
    verifiedSkills: ['Smartphone use'],
    weeklyIncomeTarget: 3600,
    earnedThisWeek: 900,
    pendingPayments: 0,
    completedShifts: 1,
    availability: ['Morning', 'Evening', 'Flexible'],
    experience: 'New worker, completed onboarding shift',
    workPreference: 'Entry-level shifts with training',
    documents: ['Aadhaar', 'PAN applied'],
  },
  {
    id: 'irfan',
    name: 'Irfan Ansari',
    hindiName: 'इरफान अंसारी',
    segment: 'daily-wage',
    role: 'Daily wage construction helper',
    location: 'Lucknow, Uttar Pradesh',
    distancePreferenceKm: 10,
    languages: ['Hindi', 'Urdu'],
    skills: ['Masonry support', 'Material loading', 'Site cleanup', 'Safety basics'],
    verifiedSkills: ['Material loading', 'Safety basics'],
    weeklyIncomeTarget: 4800,
    earnedThisWeek: 3100,
    pendingPayments: 1200,
    completedShifts: 5,
    availability: ['Morning', 'Flexible'],
    experience: '5 years site helper work',
    workPreference: 'Daily pay or next-day settlement',
    documents: ['Aadhaar', 'Bank account'],
  },
  {
    id: 'asha',
    name: 'Asha Patil',
    hindiName: 'आशा पाटिल',
    segment: 'micro-entrepreneur',
    role: 'Home tiffin micro-entrepreneur',
    location: 'Nashik, Maharashtra',
    distancePreferenceKm: 4,
    languages: ['Marathi', 'Hindi'],
    skills: ['Cooking', 'Meal planning', 'Bulk orders', 'UPI payments'],
    verifiedSkills: ['Cooking', 'UPI payments'],
    weeklyIncomeTarget: 6500,
    earnedThisWeek: 4200,
    pendingPayments: 550,
    completedShifts: 12,
    availability: ['Morning', 'Afternoon'],
    experience: 'Runs 22 daily tiffin subscriptions',
    workPreference: 'Recurring nearby orders',
    documents: ['Aadhaar', 'Bank account', 'FSSAI basic registration pending'],
    enterpriseProfile: {
      serviceName: 'Home-style veg tiffin and festival snacks',
      priceRange: 'Rs 70 - Rs 140 per meal',
      repeatCustomers: 22,
      monthlyGoal: 28000,
    },
  },
  {
    id: 'savitri',
    name: 'Savitri Bai',
    hindiName: 'सावित्री बाई',
    segment: 'farmer',
    role: 'Small farmer seeking income stability',
    location: 'Sehore, Madhya Pradesh',
    distancePreferenceKm: 15,
    languages: ['Hindi'],
    skills: ['Vegetable grading', 'Dairy care', 'Seed sorting', 'Market negotiation'],
    verifiedSkills: ['Vegetable grading', 'Dairy care'],
    weeklyIncomeTarget: 5200,
    earnedThisWeek: 1800,
    pendingPayments: 1600,
    completedShifts: 3,
    availability: ['Morning', 'Evening'],
    experience: '2.5 acre farm with seasonal vegetable sales',
    workPreference: 'Buyer linkage plus off-season work',
    documents: ['Aadhaar', 'Bank account', 'Land record photo'],
    farmProfile: {
      crop: 'Tomato and green chilli',
      season: 'Kharif harvest window',
      acreage: 2.5,
      expectedHarvestKg: 860,
    },
  },
]

export const employers: Employer[] = [
  {
    id: 'rangrez',
    name: 'Rangrez Garments Collective',
    type: 'Small manufacturer',
    location: 'Jaipur',
    reliabilityScore: 94,
    paymentClarity: 96,
    pastHires: 82,
    womenFriendly: true,
  },
  {
    id: 'swift',
    name: 'Swift Basket Fulfilment',
    type: 'Local logistics partner',
    location: 'Patna',
    reliabilityScore: 86,
    paymentClarity: 88,
    pastHires: 147,
    womenFriendly: false,
  },
  {
    id: 'suryacon',
    name: 'Surya Construction Works',
    type: 'Contractor',
    location: 'Lucknow',
    reliabilityScore: 81,
    paymentClarity: 78,
    pastHires: 64,
    womenFriendly: false,
  },
  {
    id: 'neighborhood',
    name: 'Neighborhood Orders Network',
    type: 'Local buyers',
    location: 'Nashik',
    reliabilityScore: 91,
    paymentClarity: 90,
    pastHires: 38,
    womenFriendly: true,
  },
  {
    id: 'mandi',
    name: 'Sehore Fresh Buyer Circle',
    type: 'Farmer buyer group',
    location: 'Sehore',
    reliabilityScore: 88,
    paymentClarity: 84,
    pastHires: 29,
    womenFriendly: true,
  },
]

export const jobs: Job[] = [
  {
    id: 'tailoring-batch',
    title: 'Uniform alteration batch',
    employerId: 'rangrez',
    location: 'Sanganer, Jaipur',
    distanceKm: 3.2,
    pay: 620,
    payUnit: 'day',
    schedule: '10 AM - 2 PM, 4 days',
    openings: 6,
    requiredSkills: ['Tailoring', 'Alterations', 'Quality check'],
    goodFor: ['women-returning', 'micro-entrepreneur'],
    clarity: 'Piece count and payment listed before acceptance',
  },
  {
    id: 'packing-shift',
    title: 'Entry packing shift with supervisor training',
    employerId: 'swift',
    location: 'Kankarbagh, Patna',
    distanceKm: 5.8,
    pay: 520,
    payUnit: 'shift',
    schedule: '7 AM - 1 PM, flexible days',
    openings: 18,
    requiredSkills: ['Packing', 'Inventory sorting', 'Smartphone use'],
    goodFor: ['first-time', 'daily-wage'],
    clarity: 'Training included, weekly settlement',
  },
  {
    id: 'site-helper',
    title: 'Masonry support and material movement',
    employerId: 'suryacon',
    location: 'Gomti Nagar, Lucknow',
    distanceKm: 7.6,
    pay: 780,
    payUnit: 'day',
    schedule: '8 AM - 5 PM, next 5 days',
    openings: 10,
    requiredSkills: ['Masonry support', 'Material loading', 'Safety basics'],
    goodFor: ['daily-wage'],
    clarity: 'Attendance photo and next-day settlement',
  },
  {
    id: 'tiffin-office',
    title: 'Recurring office lunch supply',
    employerId: 'neighborhood',
    location: 'College Road, Nashik',
    distanceKm: 2.4,
    pay: 2700,
    payUnit: 'week',
    schedule: '20 meals daily, Monday-Friday',
    openings: 1,
    requiredSkills: ['Cooking', 'Meal planning', 'UPI payments'],
    goodFor: ['micro-entrepreneur', 'women-returning'],
    clarity: 'Weekly prepaid order through buyer group',
  },
  {
    id: 'tomato-buyer',
    title: 'Tomato grading and buyer pickup',
    employerId: 'mandi',
    location: 'Sehore mandi route',
    distanceKm: 9.5,
    pay: 1380,
    payUnit: 'quintal',
    schedule: 'Pickup window: Thursday morning',
    openings: 12,
    requiredSkills: ['Vegetable grading', 'Market negotiation'],
    goodFor: ['farmer'],
    clarity: 'Price band locked one day before pickup',
  },
]

export const serviceRequests: ServiceRequest[] = [
  {
    id: 'school-uniforms',
    title: '12 school uniform repairs',
    customer: 'Ward 18 parent group',
    budget: 1450,
    due: '2 days',
    requiredSkills: ['Tailoring', 'Alterations'],
    status: 'New',
  },
  {
    id: 'festival-snacks',
    title: 'Diwali snack sample box',
    customer: 'Apartment welfare group',
    budget: 3200,
    due: '5 days',
    requiredSkills: ['Cooking', 'Bulk orders', 'UPI payments'],
    status: 'Quoted',
  },
  {
    id: 'monthly-tiffin',
    title: 'Monthly tiffin renewal',
    customer: 'Clinic staff circle',
    budget: 8400,
    due: 'Repeat order',
    requiredSkills: ['Cooking', 'Meal planning'],
    status: 'Repeat',
  },
]

export const farmOpportunities: FarmOpportunity[] = [
  {
    id: 'tomato-window',
    title: 'Aggregate tomato harvest for buyer pickup',
    buyer: 'Sehore Fresh Buyer Circle',
    cropOrSkill: 'Tomato',
    price: 1380,
    unit: 'quintal',
    window: 'Next 4 days',
    stabilityReason: 'Locks a price band before mandi arrival',
  },
  {
    id: 'dairy-evening',
    title: 'Evening dairy care shift',
    buyer: 'Village dairy cooperative',
    cropOrSkill: 'Dairy care',
    price: 360,
    unit: 'shift',
    window: 'Off-season income',
    stabilityReason: 'Uses existing skill when harvest income is low',
  },
  {
    id: 'seed-sorting',
    title: 'Seed sorting for local input shop',
    buyer: 'Krishi Sahayata Store',
    cropOrSkill: 'Seed sorting',
    price: 520,
    unit: 'day',
    window: '2 morning shifts',
    stabilityReason: 'Fits around farm work without travel cost',
  },
]

export const impactMetrics: ImpactMetric[] = [
  {
    label: 'Workers supported',
    value: '1,240',
    detail: 'Across daily wage, first-time, women, enterprise, and farm profiles',
  },
  {
    label: 'Income unlocked',
    value: 'Rs 18.6L',
    detail: 'Estimated weekly work value from matched opportunities',
  },
  {
    label: 'Skill passports',
    value: '830',
    detail: 'Workers with portable proof instead of informal word-of-mouth only',
  },
  {
    label: 'Reliable employers',
    value: '214',
    detail: 'Employers with clear pay terms and repeated worker acceptance',
  },
]
